[package]
name = "dawn-elaboration"
edition.workspace = true
version.workspace = true
description = "Host-side Dawn sequence elaboration and output preparation"
authors = ["Dawn"]
license = "MIT"

[dependencies]
dawn-language.workspace = true
dawn-runtime.workspace = true
indexmap.workspace = true
glam.workspace = true

[dev-dependencies]
crc32fast.workspace = true
camino.workspace = true
criterion.workspace = true
dawn-project-io.workspace = true

[[bench]]
name = "render_bench"
harness = false
