[package]
name = "dawn-device-storage"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
littlefs2 = { version = "0.8.1", default-features = false }
crc32fast = { version = "1.5.1", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["alloc", "derive"] }
serde-json-core = { version = "0.6.0", default-features = false }
