[package]
name = "donder-language"
edition.workspace = true
version.workspace = true
description = "Donder language"
authors = ["Donder"]
license = "MIT"

[features]
default = ["host"]
host = ["atomic", "dep:camino", "dep:glam", "dep:indexmap", "dep:uuid"]
atomic = []
browser = ["host", "uuid/js"]

[dependencies]
camino = { workspace = true, optional = true }
fugit.workspace = true
glam = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
rkyv.workspace = true
libm.workspace = true
micromath.workspace = true
