[package]
name = "donder-language"
edition.workspace = true
version.workspace = true
description = "Donder language"
authors = ["Donder"]
license = "MIT"

[dependencies]
camino.workspace = true
donder-runtime-types = { workspace = true, features = ["atomic"] }
indexmap.workspace = true

[lints.rust]
unnameable_types = "warn"
unreachable_pub = "warn"
