[package]
name = "donder-output"
edition.workspace = true
version.workspace = true
description = "Donder E1.31 and Art-Net output transports and FSEQ export"
authors = ["Donder"]
license = "MIT"

[dependencies]
artnet_protocol.workspace = true
donder-language.workspace = true
donder-model.workspace = true
donder-runtime.workspace = true
donder-runtime-types.workspace = true
indexmap.workspace = true
sacn.workspace = true
zstd.workspace = true

[dev-dependencies]
uuid.workspace = true
