[package]
name = "donder-output"
edition.workspace = true
version.workspace = true
description = "Donder E1.31 and Art-Net output transports"
authors = ["Donder"]
license = "MIT"

[dependencies]
artnet_protocol.workspace = true
donder-language.workspace = true
donder-elaboration.workspace = true
indexmap.workspace = true
sacn.workspace = true

[dev-dependencies]
uuid.workspace = true
