[package]
name = "donder-cli"
edition.workspace = true
version.workspace = true
description = "Donder local project command line client"
authors = ["Donder"]
license = "MIT"

[dependencies]
camino.workspace = true
clap.workspace = true
donder-project-io.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "donder"
path = "src/main.rs"
