[package]
name = "donder-cli"
edition.workspace = true
version.workspace = true
description = "Donder local project command line client"
authors = ["Donder"]
license = "MIT"

[dependencies]
camino.workspace = true
clap.workspace = true
donder-elaboration.workspace = true
donder-language.workspace = true
donder-output.workspace = true
donder-project-io.workspace = true
donder-language-server.workspace = true
lsp-server.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "donder"
path = "src/main.rs"
