[package]
name = "dawn-desktop"
edition.workspace = true
version.workspace = true
description = "Dawn desktop"
authors = ["Dawn"]
license = "MIT"
default-run = "dawn-desktop"

[dependencies]
camino.workspace = true
bytemuck.workspace = true
dawn-project-io.workspace = true
dawn-package.workspace = true
dawn-language.workspace = true
dawn-output.workspace = true
dawn-elaboration.workspace = true
glam.workspace = true
ignore.workspace = true
notify.workspace = true
indexmap.workspace = true
kira.workspace = true
reqwest.workspace = true
rfd.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serialport.workspace = true
espflash.workspace = true
esp-idf-part.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri.workspace = true
tauri-specta.workspace = true
wgpu.workspace = true
uuid.workspace = true
webbrowser.workspace = true
yaml_serde.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "dawn-desktop"
path = "src/main.rs"

[[bin]]
name = "export-bindings"
path = "src/bin/export_bindings.rs"
