import { normalizeHexColor } from "./color";

/** Runtime access to the semantic CSS palette. CSS is the sole source of color values. */
function cssColor(name: string): string {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  if (value === "") throw new Error(`Missing CSS color token: ${name}`);
  // CSS minification can shorten RGB hex tokens. Project colors and native
  // color inputs require six digits; other CSS colors retain their CSS syntax.
  return normalizeHexColor(value) ?? value;
}

function cssNumber(name: string): number {
  const value = Number.parseFloat(getComputedStyle(document.documentElement).getPropertyValue(name));
  if (!Number.isFinite(value)) throw new Error(`Missing CSS numeric token: ${name}`);
  return value;
}

function cssValue(name: string): string {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  if (value === "") throw new Error(`Missing CSS style token: ${name}`);
  return value;
}

export const THEME_TYPOGRAPHY = {
  canvas: cssValue("--donder-canvas-font"),
  canvasLabel: cssValue("--donder-canvas-label-font"),
  sequence: cssValue("--donder-sequence-font")
} as const;

export const THEME_COLORS = {
  defaultProjectColor: cssColor("--donder-default-project-color"),
  background: cssColor("--donder-bg"),
  page: cssColor("--donder-bg-page"),
  panel: cssColor("--donder-bg-panel"),
  rail: cssColor("--donder-bg-rail"),
  border: cssColor("--donder-border"),
  borderControl: cssColor("--donder-border-control"),
  text: cssColor("--donder-text"),
  textStrong: cssColor("--donder-text-strong"),
  textMuted: cssColor("--donder-text-muted"),
  textSoft: cssColor("--donder-text-soft"),
  hover: cssColor("--donder-hover"),
  accent: cssColor("--donder-accent"),
  accentBackground: cssColor("--donder-accent-bg"),
  warning: cssColor("--donder-warning"),
  danger: cssColor("--donder-danger"),
  dangerBackground: cssColor("--donder-danger-bg"),
  dangerBorder: cssColor("--donder-danger-border"),
  dangerText: cssColor("--donder-danger-text"),
  canvasBackground: cssColor("--donder-canvas-background"),
  canvasGrid: cssColor("--donder-canvas-grid"),
  canvasGuide: cssColor("--donder-canvas-guide"),
  canvasAxis: cssColor("--donder-canvas-axis"),
  canvasMajorGrid: cssColor("--donder-canvas-major-grid"),
  canvasLabel: cssColor("--donder-canvas-label"),
  layoutSelected: cssColor("--donder-layout-selected"),
  layoutLabel: cssColor("--donder-layout-label"),
  layoutEmitter: cssColor("--donder-layout-emitter"),
  automation: cssColor("--donder-automation"),
  playhead: cssColor("--donder-playhead"),
  markBlue: cssColor("--donder-mark-blue"),
  markOrange: cssColor("--donder-mark-orange"),
  markGreen: cssColor("--donder-mark-green"),
  markPink: cssColor("--donder-mark-pink"),
  markYellow: cssColor("--donder-mark-yellow"),
  markRed: cssColor("--donder-mark-red"),
  graphBlue: cssColor("--donder-graph-blue"),
  graphRed: cssColor("--donder-graph-red"),
  graphGreen: cssColor("--donder-graph-green"),
  graphYellow: cssColor("--donder-graph-yellow"),
  graphPurple: cssColor("--donder-graph-purple"),
  graphPink: cssColor("--donder-graph-pink"),
  graphGrid: cssColor("--donder-graph-grid"),
  white: cssColor("--donder-white"),
  sequencePage: cssColor("--donder-sequence-page"),
  sequencePanel: cssColor("--donder-sequence-panel"),
  sequenceLaneAlternate: cssColor("--donder-sequence-lane-alternate"),
  sequenceLaneSelected: cssColor("--donder-sequence-lane-selected"),
  sequenceGrid: cssColor("--donder-sequence-grid"),
  sequenceGridFaint: cssColor("--donder-sequence-grid-faint"),
  timelineMajor: cssColor("--donder-timeline-major"),
  timelineMinor: cssColor("--donder-timeline-minor"),
  textFaint: cssColor("--donder-text-faint"),
  overlay: cssColor("--donder-overlay"),
  clipSelected: cssColor("--donder-clip-selected"),
  clipHover: cssColor("--donder-clip-hover"),
  clipBorder: cssColor("--donder-clip-border"),
  automationFill: cssColor("--donder-automation-fill"),
  automationGraph: cssColor("--donder-automation-graph"),
  automationGraphGrid: cssColor("--donder-automation-graph-grid"),
  automationGraphMajorGrid: cssColor("--donder-automation-graph-major-grid"),
  automationClipSurface: cssColor("--donder-automation-clip-surface"),
  automationClipHeader: cssColor("--donder-automation-clip-header"),
  automationClipHeaderSelected: cssColor("--donder-automation-clip-header-selected"),
  automationCurveFill: cssColor("--donder-automation-curve-fill"),
  automationCurveShadow: cssColor("--donder-automation-curve-shadow"),
  automationPointFill: cssColor("--donder-automation-point-fill"),
  automationPointStroke: cssColor("--donder-automation-point-stroke"),
  automationClipLabel: cssColor("--donder-automation-clip-label"),
  automationClipLabelMuted: cssColor("--donder-automation-clip-label-muted"),
  automationDetached: cssColor("--donder-automation-detached"),
  accentSubtle: cssColor("--donder-accent-subtle"),
  markMarquee: cssColor("--donder-mark-marquee"),
  markMarqueeFill: cssColor("--donder-mark-marquee-fill"),
  effectMarqueeFill: cssColor("--donder-effect-marquee-fill"),
  rasterWarningOverlay: cssColor("--donder-raster-warning-overlay"),
  emptyGradient: cssColor("--donder-empty-gradient")
} as const;

export const THEME_METRICS = {
  projectPanelMinWidth: cssNumber("--donder-project-panel-min-width"),
  projectPanelMaxWidth: cssNumber("--donder-project-panel-max-width"),
  inspectorMinWidth: cssNumber("--donder-inspector-min-width"),
  inspectorMaxWidth: cssNumber("--donder-inspector-max-width"),
  canvasPadding: cssNumber("--donder-canvas-padding"),
  iconButtonSize: cssNumber("--donder-icon-button-size"),
  iconSizeSmall: cssNumber("--donder-icon-size-sm"),
  iconSizeMedium: cssNumber("--donder-icon-size-md"),
  iconSizeExtraSmall: cssNumber("--donder-icon-size-xs"),
  iconSizeCompact: cssNumber("--donder-icon-size-compact"),
  menuOffset: cssNumber("--donder-menu-offset"),
  projectTreeIndent: cssNumber("--donder-project-tree-indent"),
  projectTreeRowHeight: cssNumber("--donder-project-tree-row-height"),
  activityIconSize: cssNumber("--donder-activity-icon-size"),
  resizeHandleWidth: cssNumber("--donder-resize-handle-width"),
  controlHeightSmall: cssNumber("--donder-control-height-sm"),
  controlHeightMedium: cssNumber("--donder-control-height-md"),
  controlHeightLarge: cssNumber("--donder-control-height-lg"),
  colorPickerWidth: cssNumber("--donder-palette-picker-width"),
  colorPickerHeight: cssNumber("--donder-palette-picker-height"),
  popoverOffset: cssNumber("--donder-popover-offset"),
  popoverGap: cssNumber("--donder-popover-gap"),
  workspaceCollapseThreshold: cssNumber("--donder-workspace-collapse-threshold"),
  workspaceKeyboardStep: cssNumber("--donder-workspace-keyboard-step"),
  interactionDragThreshold: cssNumber("--donder-interaction-drag-threshold"),
  workspaceLayoutSaveDelay: cssNumber("--donder-workspace-layout-save-delay"),
  tooltipDelayMs: cssNumber("--donder-tooltip-delay-ms"),
  searchDebounceMs: cssNumber("--donder-search-debounce-ms"),
  documentAnalysisDelayMs: cssNumber("--donder-document-analysis-delay-ms"),
  sequenceLeftGutter: cssNumber("--donder-sequence-left-gutter"),
  sequenceTop: cssNumber("--donder-sequence-top"),
  sequenceAudioStripTop: cssNumber("--donder-sequence-audio-strip-top"),
  sequenceInitialPixelsPerSecond: cssNumber("--donder-sequence-initial-pixels-per-second"),
  sequenceInitialLaneHeight: cssNumber("--donder-sequence-initial-lane-height"),
  sequenceLaneResizeIndicatorHeight: cssNumber("--donder-sequence-lane-resize-indicator-height"),
  sequenceLaneResizeHitHeight: cssNumber("--donder-sequence-lane-resize-hit-height"),
  sequenceMinPixelsPerSecond: cssNumber("--donder-sequence-min-pixels-per-second"),
  sequenceMaxPixelsPerSecond: cssNumber("--donder-sequence-max-pixels-per-second"),
  sequenceMaxZoomPixelsPerSecond: cssNumber("--donder-sequence-max-zoom-pixels-per-second"),
  sequenceMinLaneHeight: cssNumber("--donder-sequence-min-lane-height"),
  sequenceMaxLaneHeight: cssNumber("--donder-sequence-max-lane-height"),
  graphGridGap: cssNumber("--donder-graph-grid-gap"),
  graphNodeStrokeWidth: cssNumber("--donder-graph-node-stroke-width"),
  curveEditorWidth: cssNumber("--donder-curve-editor-width"),
  curveEditorHeight: cssNumber("--donder-curve-editor-height"),
  canvasPointHitRadius: cssNumber("--donder-canvas-point-hit-radius"),
  scrollbarThumbMinHeight: cssNumber("--donder-scrollbar-thumb-min-height"),
  graphEdgeInteractionWidth: cssNumber("--donder-graph-edge-interaction-width"),
  graphNodeMinHeight: cssNumber("--donder-graph-node-min-height"),
  graphNodeMinWidth: cssNumber("--donder-graph-node-min-width"),
  graphNodeStrokeWidthStrong: cssNumber("--donder-graph-node-stroke-width-strong"),
  graphPointRadius: cssNumber("--donder-graph-point-radius"),
  graphPointRadiusSelected: cssNumber("--donder-graph-point-radius-selected"),
  sequenceEffectResizeHitWidth: cssNumber("--donder-sequence-effect-resize-hit-width"),
  sequenceMarkHitRadius: cssNumber("--donder-sequence-mark-hit-radius"),
  visualLineWidth: cssNumber("--donder-visual-line-width"),
  visualLineWidthStrong: cssNumber("--donder-visual-line-width-strong"),
  visualMinSize: cssNumber("--donder-visual-min-size"),
  visualHairlineOffset: cssNumber("--donder-visual-hairline-offset"),
  sequenceLabelX: cssNumber("--donder-sequence-label-x"),
  sequenceLabelYOffset: cssNumber("--donder-sequence-label-y-offset"),
  sequenceClipMinWidth: cssNumber("--donder-sequence-clip-min-width"),
  sequenceClipMinHeight: cssNumber("--donder-sequence-clip-min-height"),
  sequenceClipSlotOffset: cssNumber("--donder-sequence-clip-slot-offset"),
  sequenceClipHandleHalfWidth: cssNumber("--donder-sequence-clip-handle-half-width"),
  sequenceClipHandleHeight: cssNumber("--donder-sequence-clip-handle-height"),
  sequenceClipHandleInset: cssNumber("--donder-sequence-clip-handle-inset"),
  sequenceMarkerHalfWidth: cssNumber("--donder-sequence-marker-half-width"),
  sequenceMarkerWidth: cssNumber("--donder-sequence-marker-width"),
  sequenceMarkerHeight: cssNumber("--donder-sequence-marker-height"),
  sequenceMarkerDashSize: cssNumber("--donder-sequence-marker-dash-size"),
  automationGraphPaddingMin: cssNumber("--donder-automation-graph-padding-min"),
  automationGraphPaddingMax: cssNumber("--donder-automation-graph-padding-max"),
  automationGraphPaddingRatio: cssNumber("--donder-automation-graph-padding-ratio"),
  automationCurveWidth: cssNumber("--donder-automation-curve-width"),
  automationCurveShadowWidth: cssNumber("--donder-automation-curve-shadow-width"),
  automationPointRadius: cssNumber("--donder-automation-point-radius"),
  automationPointRadiusSelected: cssNumber("--donder-automation-point-radius-selected"),
  curvePointRadius: cssNumber("--donder-curve-point-radius"),
  curvePointRadiusSelected: cssNumber("--donder-curve-point-radius-selected"),
  automationGridColumns: cssNumber("--donder-automation-grid-columns"),
  automationGridRows: cssNumber("--donder-automation-grid-rows"),
  automationRowMinHeight: cssNumber("--donder-automation-row-min-height"),
  automationRowMaxHeight: cssNumber("--donder-automation-row-max-height"),
  automationRowHeightRatio: cssNumber("--donder-automation-row-height-ratio"),
  automationClipRadius: cssNumber("--donder-automation-clip-radius"),
  automationClipHeaderHeight: cssNumber("--donder-automation-clip-header-height"),
  automationClipLabelInset: cssNumber("--donder-automation-clip-label-inset"),
  automationClipLabelBaseline: cssNumber("--donder-automation-clip-label-baseline"),
  automationClipLabelMinWidth: cssNumber("--donder-automation-clip-label-min-width"),
  automationDetachedStripeWidth: cssNumber("--donder-automation-detached-stripe-width"),
  waveformAmplitudeInset: cssNumber("--donder-waveform-amplitude-inset"),
  timelineLabelX: cssNumber("--donder-timeline-label-x"),
  timelineLabelY: cssNumber("--donder-timeline-label-y"),
  timelineMinLabelWidth: cssNumber("--donder-timeline-min-label-width"),
  timelineMinGridWidth: cssNumber("--donder-timeline-min-grid-width"),
  rasterWarningSizeMin: cssNumber("--donder-raster-warning-size-min"),
  rasterWarningSizeMax: cssNumber("--donder-raster-warning-size-max"),
  rasterWarningInset: cssNumber("--donder-raster-warning-inset"),
  automationLabelOffsetY: cssNumber("--donder-automation-label-offset-y"),
  sequenceDragThreshold: cssNumber("--donder-sequence-drag-threshold"),
  sequenceWheelZoomScale: cssNumber("--donder-sequence-wheel-zoom-scale"),
  spatialWheelZoomScale: cssNumber("--donder-spatial-wheel-zoom-scale"),
  sequenceScrubStep: cssNumber("--donder-sequence-scrub-step"),
  sequenceNudgeStep: cssNumber("--donder-sequence-nudge-step"),
  sequenceShiftedNudgeStep: cssNumber("--donder-sequence-shifted-nudge-step"),
  markCullPadding: cssNumber("--donder-mark-cull-padding"),
  markSelectedHalfWidth: cssNumber("--donder-mark-selected-half-width"),
  markOverlayOpacity: cssNumber("--donder-mark-overlay-opacity"),
  markStripOpacity: cssNumber("--donder-mark-strip-opacity"),
  opacityFull: cssNumber("--donder-opacity-full"),
  canvasLabelLeftInset: cssNumber("--donder-canvas-label-left-inset"),
  canvasLabelRightInset: cssNumber("--donder-canvas-label-right-inset"),
  canvasLabelBottomInset: cssNumber("--donder-canvas-label-bottom-inset"),
  canvasLabelTopInset: cssNumber("--donder-canvas-label-top-inset"),
  canvasLabelXOffset: cssNumber("--donder-canvas-label-x-offset"),
  canvasLabelYOffset: cssNumber("--donder-canvas-label-y-offset"),
  layoutPointRadius: cssNumber("--donder-layout-point-radius"),
  layoutSelectedPointRadius: cssNumber("--donder-layout-selected-point-radius"),
  layoutEmitterHalfSize: cssNumber("--donder-layout-emitter-half-size"),
  layoutLabelOffsetX: cssNumber("--donder-layout-label-offset-x"),
  layoutLabelOffsetY: cssNumber("--donder-layout-label-offset-y"),
  layoutSelectionDash: cssNumber("--donder-layout-selection-dash"),
  layoutSelectionGap: cssNumber("--donder-layout-selection-gap"),
  spatialPointRadius: cssNumber("--donder-spatial-point-radius"),
  spatialHitRadius: cssNumber("--donder-spatial-hit-radius"),
  spatialPanThreshold: cssNumber("--donder-spatial-pan-threshold"),
  layoutSelectedAlpha: cssNumber("--donder-layout-selected-alpha"),
  layoutUnselectedAlpha: cssNumber("--donder-layout-unselected-alpha"),
  layoutLabelAlpha: cssNumber("--donder-layout-label-alpha"),
  layoutSelectedLineWidth: cssNumber("--donder-layout-selected-line-width"),
  layoutUnselectedLineWidth: cssNumber("--donder-layout-unselected-line-width"),
  layoutLineWidth: cssNumber("--donder-layout-line-width"),
  layoutLineWidthSelected: cssNumber("--donder-layout-line-width-selected")
} as const;
