[package]
name = "dawn-project-io"
edition.workspace = true
version.workspace = true
description = "Dawn project import and export IO"
authors = ["Dawn"]
license = "MIT"

[dependencies]
camino.workspace = true
dawn-package.workspace = true
dawn-language.workspace = true
dur.workspace = true
indexmap.workspace = true
marked-yaml.workspace = true
pathdiff.workspace = true
serde.workspace = true
serde_path_to_error.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
uuid.workspace = true
tempfile.workspace = true

[dev-dependencies]
dawn-elaboration.workspace = true
semver.workspace = true
